### ISSUE TITLE
status.json wishlist

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/test_registry#5]
Following conversation with @robredpath - this is my wishlist for the contents of the json output after completion of #4. 

For each file record the following information:

(NB - there's a question for me over whether this should be "for every `fundingOrganization` in every file" - theoretically a publisher could include more than one funder in a file?)

- list of the funders included
- list of the currencies used
- earliest awardDate
- latest awardDate
- earliest lastModified
- latest lastModified
- total number of rows (& split by currency)
- total value of grants (split by currency)

- for each field in the file:
	- field name
	- number of null/blank values
	- (_future development_) - number of values matching the required format (eg conform to regex)
	- (_future development_) - for fields that can be externally validated (eg identifiers) - number of values that are externally verified
	- whether the field appears in the 360 giving standard (plus guess at the field type if a non-standard field)

- required fields that do not appear in file
- recommended fields that do not appear in file

- something on location fields, giving a breakdown of the number of location fields found (eg X records have 0 beneficiary location records, Y records have 1 beneificiary location, Z records have 2 beneficiary location)

**Comment by Bjwebb** [comment]
Thanks for putting together this list!

We've been doing some work on `status.json` at https://github.com/ThreeSixtyGiving/datagetter/pull/6. It is now accessible at 
https://storage.googleapis.com/datagetter-360giving-output/branch/master/status.json

I think all the fields you want will be in under the `datagetter_aggregates` key in each dataset:

We have the following:

- earliest awardDate: `min_award_date`
- latest awardDate: `max_award_date`
- list of the currencies used: they keys within `currencies`
- total number of rows (& split by currency): `count` and `currencies/XXX/count`
- total value of grants (split by currency): `currencies/XXX/total_amount`

We don't yet have:

- list of the funders included https://github.com/ThreeSixtyGiving/datagetter/issues/8
- earliest lastModified https://github.com/ThreeSixtyGiving/datagetter/issues/9
- latest lastModified https://github.com/ThreeSixtyGiving/datagetter/issues/9

- for each field in the file: https://github.com/ThreeSixtyGiving/datagetter/issues/11
	- field name
	- number of null/blank values
	- (_future development_) - number of values matching the required format (eg conform to regex)
	- (_future development_) - for fields that can be externally validated (eg identifiers) - number of values that are externally verified
	- whether the field appears in the 360 giving standard (plus guess at the field type if a non-standard field)

- required fields that do not appear in file https://github.com/ThreeSixtyGiving/datagetter/issues/10
- recommended fields that do not appear in file https://github.com/ThreeSixtyGiving/datagetter/issues/10

- something on location fields, giving a breakdown of the number of location fields found (eg X records have 0 beneficiary location records, Y records have 1 beneificiary location, Z records have 2 beneficiary location) https://github.com/ThreeSixtyGiving/datagetter/issues/13

As I've added new issues for each point, I'm closing this issue. Also, work has moved to the https://github.com/ThreeSixtyGiving/datagetter repo, rather than this one, so please report any additional issues there.
